#! /bin/sh

cat $1 |
grep -E '<td>.+</td>' |
awk 'NR % 2 == 0' |
tr [:upper:] [:lower:] |
sed 's/<\/*[a-zA-Z]*>//g' |
sed 's/`/'\''/g' |
sed 's/ \{2,\}//' |
sed 's/,* /\n/g' |
sed '/[^pk'\''mnwlhaeiou]/d' |
tr -s '\n' |
sort -u 

