#! /bin/sh

RESULT=$(find ${1} -maxdepth 1 -type f | sort)
OUTERVAR=0
while read line; do
    OUTERVAR=$(($OUTERVAR+1))
    INNERVAR=0
    
    if test ! -r "$line"; then
	echo "$line not readable. Skipping file."
	continue
    fi

    while read line2; do
	INNERVAR=$(($INNERVAR+1))
	if test $INNERVAR -le $OUTERVAR || test ! -r "$line2"; then
	    continue
	fi
	if cmp -s "$line" "$line2"; then
	    ln -f "$line" "$line2"
	fi
    done <<< "$RESULT"
done <<< "$RESULT"



